Name:           ros-hydro-kobuki-testsuite
Version:        0.5.8
Release:        0%{?dist}
Summary:        ROS kobuki_testsuite package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/kobuki_testsuite
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-kobuki-node
Requires:       ros-hydro-message-runtime
Requires:       ros-hydro-python-orocos-kdl
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-std-msgs
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-kobuki-node
BuildRequires:  ros-hydro-message-generation
BuildRequires:  ros-hydro-python-orocos-kdl
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-std-msgs

%description
Kobuki test suite: this package provides tools to thoroughly test Kobuki's
hardware.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Wed Aug 20 2014 Jorge Santos Simon <jorge@yujinrobot.com> - 0.5.8-0
- Autogenerated by Bloom

* Mon Aug 18 2014 Jorge Santos Simon <jorge@yujinrobot.com> - 0.5.7-0
- Autogenerated by Bloom

