Name:           ros-hydro-kobuki-auto-docking
Version:        0.5.8
Release:        0%{?dist}
Summary:        ROS kobuki_auto_docking package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/kobuki_auto_docking
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-actionlib
Requires:       ros-hydro-actionlib-msgs
Requires:       ros-hydro-ecl-geometry
Requires:       ros-hydro-ecl-linear-algebra
Requires:       ros-hydro-ecl-threads
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-kdl-conversions
Requires:       ros-hydro-kobuki-dock-drive
Requires:       ros-hydro-kobuki-msgs
Requires:       ros-hydro-message-filters
Requires:       ros-hydro-nav-msgs
Requires:       ros-hydro-nodelet
Requires:       ros-hydro-pluginlib
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-rospy
Requires:       ros-hydro-std-msgs
Requires:       ros-hydro-yocs-cmd-vel-mux
BuildRequires:  ros-hydro-actionlib
BuildRequires:  ros-hydro-actionlib-msgs
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-ecl-geometry
BuildRequires:  ros-hydro-ecl-linear-algebra
BuildRequires:  ros-hydro-ecl-threads
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-kdl-conversions
BuildRequires:  ros-hydro-kobuki-dock-drive
BuildRequires:  ros-hydro-kobuki-msgs
BuildRequires:  ros-hydro-message-filters
BuildRequires:  ros-hydro-nav-msgs
BuildRequires:  ros-hydro-nodelet
BuildRequires:  ros-hydro-pluginlib
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-std-msgs

%description
Automatic docking for Kobuki: Users owning a docking station for Kobuki can use
this tool to let Kobuki find its nest autonomously.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Wed Aug 20 2014 Younghun Ju <yhju@yujinrobot.com> - 0.5.8-0
- Autogenerated by Bloom

* Mon Aug 18 2014 Younghun Ju <yhju@yujinrobot.com> - 0.5.7-0
- Autogenerated by Bloom

