Name:           ros-hydro-kobuki-keyop
Version:        0.5.7
Release:        0%{?dist}
Summary:        ROS kobuki_keyop package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/kobuki_keyop
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-ecl-exceptions
Requires:       ros-hydro-ecl-threads
Requires:       ros-hydro-ecl-time
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-kobuki-msgs
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-std-msgs
Requires:       ros-hydro-std-srvs
Requires:       ros-hydro-yocs-cmd-vel-mux
Requires:       ros-hydro-yocs-velocity-smoother
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-ecl-exceptions
BuildRequires:  ros-hydro-ecl-threads
BuildRequires:  ros-hydro-ecl-time
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-kobuki-msgs
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-std-msgs
BuildRequires:  ros-hydro-std-srvs

%description
Keyboard teleoperation for Kobuki: relays commands from a keyboard to Kobuki.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Mon Aug 18 2014 Daniel Stonier <stonier@yujinrobot.com> - 0.5.7-0
- Autogenerated by Bloom

