Name:           ros-hydro-kobuki-node
Version:        0.5.8
Release:        0%{?dist}
Summary:        ROS kobuki_node package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/kobuki_node
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-angles
Requires:       ros-hydro-diagnostic-aggregator
Requires:       ros-hydro-diagnostic-msgs
Requires:       ros-hydro-diagnostic-updater
Requires:       ros-hydro-ecl-exceptions
Requires:       ros-hydro-ecl-sigslots
Requires:       ros-hydro-ecl-streams
Requires:       ros-hydro-ecl-threads
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-kobuki-driver
Requires:       ros-hydro-kobuki-ftdi
Requires:       ros-hydro-kobuki-keyop
Requires:       ros-hydro-kobuki-msgs
Requires:       ros-hydro-kobuki-safety-controller
Requires:       ros-hydro-nav-msgs
Requires:       ros-hydro-nodelet
Requires:       ros-hydro-pluginlib
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-rospy
Requires:       ros-hydro-rviz
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-std-msgs
Requires:       ros-hydro-tf
BuildRequires:  ros-hydro-angles
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-diagnostic-msgs
BuildRequires:  ros-hydro-diagnostic-updater
BuildRequires:  ros-hydro-ecl-exceptions
BuildRequires:  ros-hydro-ecl-sigslots
BuildRequires:  ros-hydro-ecl-streams
BuildRequires:  ros-hydro-ecl-threads
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-kobuki-driver
BuildRequires:  ros-hydro-kobuki-ftdi
BuildRequires:  ros-hydro-kobuki-keyop
BuildRequires:  ros-hydro-kobuki-msgs
BuildRequires:  ros-hydro-kobuki-safety-controller
BuildRequires:  ros-hydro-nav-msgs
BuildRequires:  ros-hydro-nodelet
BuildRequires:  ros-hydro-pluginlib
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-std-msgs
BuildRequires:  ros-hydro-tf

%description
ROS nodelet for Kobuki: ROS wrapper for the Kobuki driver.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Wed Aug 20 2014 Daniel Stonier <stonier@yujinrobot.com> - 0.5.8-0
- Autogenerated by Bloom

* Mon Aug 18 2014 Daniel Stonier <stonier@yujinrobot.com> - 0.5.7-0
- Autogenerated by Bloom

